export const GET_REQUEST = "GET_REQUEST"
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS"
export const GET_REQUEST_FAILURE = "GET_REQUEST_FAILURE"

export const PATCH_CART_REQUEST_SUCCESS = "PATCH_CART_REQUEST_SUCCESS"
export const PATCH_ORDER_REQUEST_SUCCESS = "PATCH_ORDER_REQUEST_SUCCESS"
