export const ADMIN_DELETE_REQUEST = 'ADMIN_DELETE_REQUEST'
export const ADMIN_EDIT_REQUEST = 'ADMIN_EDIT_REQUEST'

// Adding a Product
export const POST_PRODUCT_REQUEST = 'POST_PRODUCT_REQUEST';
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
export const POST_PRODUCT_FAILURE = 'POST_PRODUCT_FAILURE';

export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';
